version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    container_name: snipshare-postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=snipshare
    volumes:
      - snipshare-postgresql:/var/lib/postgresql/data

volumes:
  snipshare-postgresql:
    driver: local